import { describe, expect, it } from "vitest";
import { sanitizeMaigretHtmlReport } from "./maigret-report";

describe("sanitizeMaigretHtmlReport", () => {
  it("keeps report content while removing scripts, provider branding, and external bootstrap dependencies", () => {
    const sanitized = sanitizeMaigretHtmlReport(`<!doctype html>
      <html>
        <head>
          <title>khstar104 -- Maigret username search report</title>
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        </head>
        <body>
          <h4>Username search report for khstar104</h4>
          <small>Generated by <a href="https://github.com/soxoj/maigret">Maigret</a> at 2026-06-11 05:03:17</small>
          <a href="https://blog.naver.com/khstar104" target="_blank">Naver</a>
          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
          <script>alert("x")</script>
        </body>
      </html>`);

    expect(sanitized).toContain("khstar104 -- ID 도플갱어 리포트");
    expect(sanitized).toContain("ID 도플갱어 리포트: khstar104");
    expect(sanitized).toContain("Generated 2026-06-11 05:03:17");
    expect(sanitized).toContain("https://blog.naver.com/khstar104");
    expect(sanitized).toContain("rel=\"noopener noreferrer\"");
    expect(sanitized).toContain("id-doppelganger-source-report");
    expect(sanitized).not.toContain("Maigret");
    expect(sanitized).not.toContain("<script");
    expect(sanitized).not.toContain("stackpath.bootstrapcdn.com");
    expect(sanitized).not.toContain("jquery");
  });

  it("inlines Maigret's default unknown avatar to avoid noisy blocked image requests", () => {
    const sanitized = sanitizeMaigretHtmlReport(`
      <html>
        <head></head>
        <body>
          <img class="card-img-right" src="https://i.imgur.com/040fmbw.png" alt="unknown">
          <img src="https://avatars.githubusercontent.com/u/1?v=4" alt="real profile">
        </body>
      </html>`);

    expect(sanitized).not.toContain("https://i.imgur.com/040fmbw.png");
    expect(sanitized).toContain("data:image/svg+xml");
    expect(sanitized).toContain("https://avatars.githubusercontent.com/u/1?v=4");
  });
});
