const reportCss = `
<style id="id-doppelganger-source-report">
  body { margin: 0; background: #ffffff; color: #191f28; font-family: Pretendard, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
  .container { width: min(1080px, calc(100% - 28px)); margin: 0 auto; padding: 18px 0 26px; }
  .card { border: 1px solid #e5e8eb; border-radius: 8px; background: #fff; overflow: hidden; }
  .card-body { padding: 16px; }
  .row-mb, .mb-4 { margin-bottom: 14px; }
  .flex-md-row { display: flex; gap: 16px; align-items: stretch; }
  .card-img-right { flex: 0 0 132px; width: 132px !important; height: 132px !important; border-right: 1px solid #edf0f2; background: #f7f8fa; object-fit: cover !important; }
  h3, h4, h5 { margin: 0 0 8px; line-height: 1.25; }
  h3 { font-size: 22px; }
  h4 { font-size: 24px; }
  h5 { font-size: 18px; }
  a { color: #0f62fe; word-break: break-all; }
  .text-muted { color: #6b7684; }
  .card-text { margin: 7px 0; color: #4e5968; line-height: 1.55; }
  @media (max-width: 640px) {
    .flex-md-row { display: block; }
    .card-img-right { width: 100% !important; height: 180px !important; border-right: 0; border-bottom: 1px solid #edf0f2; }
  }
</style>`;

const maigretUnknownAvatarUrl = "https://i.imgur.com/040fmbw.png";
const inlineUnknownAvatar =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180' viewBox='0 0 180 180'%3E%3Crect width='180' height='180' fill='%23f2f4f6'/%3E%3Ccircle cx='90' cy='72' r='32' fill='%23b0b8c1'/%3E%3Cpath d='M42 154c8-34 31-52 48-52s40 18 48 52' fill='%23b0b8c1'/%3E%3C/svg%3E";

export function sanitizeMaigretHtmlReport(html: string) {
  const withoutScripts = html
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, "")
    .replace(/<link\b[^>]*?(?:bootstrap|stackpath|cdnjs|code\.jquery)[^>]*?>/gi, "")
    .replace(/\s+integrity=(["']).*?\1/gi, "")
    .replace(/\s+crossorigin=(["']).*?\1/gi, "")
    .replaceAll(maigretUnknownAvatarUrl, inlineUnknownAvatar);

  const withoutProviderBranding = withoutScripts
    .replace(/Generated by\s*<a\b[^>]*>\s*Maigret\s*<\/a>\s*(?:at\s*)?/gi, "Generated ")
    .replace(/Generated by\s*Maigret\s*(?:at\s*)?/gi, "Generated ");

  const withSafeLinks = withoutProviderBranding.replace(/<a\b([^>]*)>/gi, (match, attributes: string) => {
    if (!/\btarget\s*=/i.test(attributes)) return match;
    if (/\brel\s*=/i.test(attributes)) return match;
    return `<a${attributes} rel="noopener noreferrer">`;
  });

  if (/<\/head>/i.test(withSafeLinks)) {
    return withSafeLinks.replace(/<\/head>/i, `${reportCss}</head>`);
  }

  return `${reportCss}${withSafeLinks}`;
}
